"""
PR Validation Pipeline - Data Models

Issue-aware correctness validation models.
Separate from Repo Audit to enforce architectural separation.
"""
from typing import List, Literal, Optional
from datetime import datetime
from beanie import Document, PydanticObjectId
from pydantic import Field, BaseModel


# Evidence Model

class Evidence(BaseModel):
    """
    Immutable proof for checklist validation.
    
    Contract:
    - source: Which engine provided this evidence
    - verdict: pass/fail/unknown
    - explanation: Human-readable reasoning
    - traceable: Links to code location
    """
    checklist_item_id: str
    source: Literal["codeant", "qodo", "quantum", "manual"]
    verdict: Literal["pass", "fail", "unknown"]
    explanation: str
    
    # Code traceability
    file_path: Optional[str] = None
    line_number: Optional[int] = None
    snippet: Optional[str] = None
    
    # Metadata
    generated_at: datetime = Field(default_factory=datetime.utcnow)


# Checklist Models

class ChecklistItemResult(BaseModel):
    """Result for a single checklist item"""
    item_id: str
    text: str
    required: bool
    status: Literal["pass", "fail", "pending", "skipped"]
    evidence: List[Evidence] = []


class Checklist(Document):
    """
    Immutable checklist generated by Quantum.
    
    Contract:
    - Tied to specific issue version
    - Versioned for issue updates
    - Never modified after creation
    """
    issue_id: PydanticObjectId
    issue_number: int
    version: int  # Increments if issue edited
    
    items: List[dict]  # Raw checklist items from Quantum
    
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    immutable: bool = True
    
    class Settings:
        name = "checklists"
        indexes = ["issue_id", "version"]


# PR Validation Run

class PRRun(Document):
    """
    Single PR validation execution.
    
    Contract:
    - One run per PR validation attempt
    - Links to checklist used
    - Produces verdict
    """
    pr_id: PydanticObjectId
    pr_number: int
    repo_id: PydanticObjectId
    
    checklist_id: Optional[PydanticObjectId] = None  # May be None if no linked issue
    
    status: Literal["pending", "running", "completed", "failed"]
    
    # Timestamps
    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None
    
    # Results stored in Verdict document
    
    class Settings:
        name = "pr_runs"
        indexes = ["pr_id", "status", "started_at"]


# Verdict Model

class Verdict(Document):
    """
    Final judgment on PR validation.
    
    Contract:
    - Immutable once generated
    - Evidence-backed
    - Checklist-traceable
    """
    pr_run_id: PydanticObjectId
    pr_number: int
    
    result: Literal["PASS", "PARTIAL", "FAIL"]
    
    # Checklist results
    checklist_results: List[ChecklistItemResult] = []
    
    # Overall summary
    summary: Optional[str] = None
    
    # Metadata
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    immutable: bool = True
    
    class Settings:
        name = "verdicts"
        indexes = ["pr_run_id", "pr_number"]
